### ISSUE TITLE
LIDAR_AND_IMAGES.bag is missing

### ISSUE THREAD

**Issue by timeamagyar** [brian-h-wang/ldls_ros#1]
Hi Brian,
thanks for sharing your work! Would it be possible for you to kindly share the example LIDAR_AND_IMAGES.bag file you have mentioned in your readme. 
Did you use kitti2bag? The topics you reference in your code are not available in the kitti2bag output rosbags..

Thanks and kind regards,
Timea

**Comment by brian-h-wang** [comment]
Hi Timea - Unfortunately I don't have a sample dataset available to share now ("LIDAR_AND_IMAGES" was just intended as a placeholder path for a user-provided rosbag), but I've updated the readme to describe which variables should be changed to read in the correct ROS topic names from the rosbag input. I haven't used kitti2bag, but as long as it includes an image topic and velodyne topic with type sensor_msgs/PointCloud2, should be able to get it to work by changing the topic name variables. Thanks!
